spring:
  application:
    name: template
  
  jackson:
    property-naming-strategy: SNAKE_CASE

  datasource:
    url: jdbc:mysql://localhost:3306/aigreentick_schema
    username: root
    password: meenagaming12@#
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000


  jpa:
    hibernate:
      ddl-auto: validate  # ‚Üê THIS IS WHAT YOU NEED
    show-sql: false  # Set to true to see SQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true


# ---------------- WhatsApp Service ----------------
whatsapp-service:
  base-url: https://graph.facebook.com
  api-version: v23.0